### ISSUE TITLE
hello!Appear the following questions

### ISSUE THREAD

**Issue by oe77** [jelmerdereus/go-sslscan#1]
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by jelmerdereus** [comment]
it does a connection test, and if it's not a TCP port it reports an error for that host.
If this machine is unreachable this is the proper behavior. Can you confirm?

if it is a reachable TCP port it assumes it has an SSL socket. I can change this into another test before running cmd.Run() on [rbsec/ssltest](https://github.com/rbsec/ssltest)

**Comment by oe77** [comment]
Hello!
My English is not very good, I am sorry.
Why not report generation?

![xshot-0043](https://cloud.githubusercontent.com/assets/12007315/11974330/13ed05ac-a99e-11e5-8f9d-e8d1592a19b3.png)

**Comment by jelmerdereus** [comment]
it should report the results of the other sslscan jobs when you press F5 (it does not autorefresh)

**Comment by oe77** [comment]
![xshot-0044](https://cloud.githubusercontent.com/assets/12007315/11974611/bb079562-a9a0-11e5-8d98-7753c3f8ec32.png)
I have tried to refresh, but the results are still not out!

**Comment by jelmerdereus** [comment]
oe77 Please check http://localhost:8080 in your browser since it will render the table for you with JavaScript

**Comment by jelmerdereus** [comment]
I have extended the README.md to explain that you need the browser to view the results.

**Comment by oe77** [comment]
Thank you！
normal use！

![xshot-0045](https://cloud.githubusercontent.com/assets/12007315/11975123/a7af9f5a-a9a5-11e5-8afb-2876ba6dc3d7.png)

**Comment by jelmerdereus** [comment]
thanks for your feedback @oe77 you pointed out something that was missing in the documentation. I have extended it. have a great Christmas!
